FamiStudio/Source/IO/FamitrackerInstrumentFile.cs

Hello!
As I said the other day, I made a change to import the first value of the duty cycle.
Please confirm this change.

Duty cycle first value support

---

Docs/docs/importexport.md

Document the ReverseBits attribute.

---

FamiStudio/Source/IO/VideoFile.cs
FamiStudio/Source/UI/Common/ExportDialog.cs
FamiStudio/Source/UI/Common/Sequencer.cs

Reworked video export to use a single-pass of ffmpeg
Also fixed a compile error in Sequencer.cs and the export dialog box
size

Reworked export to use a single-pass of ffmpeg

---

Docs/docs/soundengine.md
Setup/PackageSoundEngine.cmd

Check commit messages for details

Update c binding export

---

FamiStudio/Source/UI/Desktop/TutorialDialog.cs

Changed "Always keep **and** eye on the TOOLTIPS!" to "Always keep **an** eye on the TOOLTIPS!"

Fixed typo in step 7 of the tutorial

---

Docs/docs/song.md

Changed "definately" to "definitely"

Fix spelling error in song.md

---

README.md

In issue #169 i had an issue regarding pipewire, and until that is fixed, we might as well leave it there.

Added info to Readme regarding #169

---

FamiStudio/Source/Player/NesApu.cs
FamiStudio/Source/Player/RegisterInterpreter.cs
FamiStudio/Source/UI/Common/ProjectExplorer.cs

More details in the commits, especially in the latter one
Tested on Microsoft Windows 10 and Linux Mint 21

Fixes + FDS Mod Speed & Depth being displayed

---

FamiStudio/Localization/FamiStudio.spa.ini

Translated: [ExpansionType], [ChannelType], [EnvelopeType], [MidiPolyphonyBehavior], [MidiExportInstrumentMode], [MidiExportInstrumentMode], [ExportDialog] (Incomplete, only audio part).

Test 2 (I´m trying)

---

FamiStudio/Localization/FamiStudio.spa.ini

Translated: Video oscilloscope/pianoroll, ROM export and Midi import/export stuff...

Test 3 (Ufff this is kinda hard)

---

FamiStudio/Localization/FamiStudio.spa.ini

What the title says. Everything has been translated, now all that remains is to review...

Test 11 (Near final)

---

FamiStudio/Localization/FamiStudio.por.ini

Portuguese PR 1

---

FamiStudio/Localization/FamiStudio.spa.ini

Added the lines NoneName and NoneInstrumentName. [WavePresetType] and # Keyboard shortcuts were added too (By me!👍).

Test 12 (Probably final version)

---

FamiStudio/Localization/FamiStudio.eng.ini
FamiStudio/Source/ChannelStates/ChannelStateEPSMSquare.cs
FamiStudio/Source/ChannelStates/ChannelStateS5B.cs
FamiStudio/Source/IO/WaveFile.cs
FamiStudio/Source/Player/NesApu.cs
FamiStudio/Source/Player/RegisterInterpreter.cs
FamiStudio/Source/Project/DPCMSample.cs
FamiStudio/Source/UI/Common/ProjectExplorer.cs

Not yet successfully working on Mac for some reason, please only merge if How2Bboss' tests are successful

Register view untiement, Hz kHz semitones localization

---

FamiStudio/Localization/FamiStudio.por.ini

Up to line 542. _That's roughly halfway there!_
Added a few sections I had missed before (namely `[VideoResolution]` and `[Settings]`).
Feeling more confident about word choices and the translation in general; _still_ think certain bits are slightly too long.

Second portuguese translation PR

---

FamiStudio/Localization/FamiStudio.spa.ini

change 'vertical' to 'retrato' and 'horizontal' to 'panorámica' in a few lines

Loc consistency changes

---

FamiStudio/Localization/FamiStudio.por.ini

Fully done, wow!
Now onto typos and the like...

First pass of Portuguese translation done

---

FamiStudio/Localization/FamiStudio.zho.ini

Sorry missed this
Probably the last PR before 4.1.0

Update Chinese L18n for VGM Stuff

---

FamiStudio/Localization/FamiStudio.zho.ini

not sure if i can squeeze this in

Chinese L18n Hotfix

---

Docs/docs/thanks.md

How2bboss patch 1

---

Docs/docs/expansion.md
Docs/docs/import.md
Docs/docs/install.md
Docs/docs/instruments.md
Docs/docs/privacy.md
Docs/docs/song.md
Docs/docs/soundengine.md

I Just fixed some Spelling Errors in the Docs :D

Fixed some Spelling Errors in the Docs

---

FamiStudio/Localization/FamiStudio.spa.ini

I believe this is the first one.,.,.

First Spanish 4.2.0 update

---

FamiStudio/Localization/FamiStudio.por.ini

Updates translation and fixes errors.

PT-BR Translation update

---

FamiStudio/Source/IO/FamitoneMusicFile.cs

As part of the changes for modular EPSM support, the header also needs to be changed to disable the pointers, as the code in the driver is designed to treat them as missing from the header. Basically, without the change the modular EPSM code doesn't work at all, as it can't read the correct channel pointers from the header.
This is a bug fix change as the EPSM channel defines will *break* without the channels getting removed from the header as well.

Fix header to allow for conditionally included EPSM channels

---

FamiStudio/Source/UI/Common/ParamProviders.cs

Tested on linux only, renders fine and reflects the envelope shape as intended

EPSM SSG-EG shape is now graphics

---

FamiStudio/Localization/FamiStudio.deu.ini

Now we can Fami our Studios in glorious Hochdeutsch

Added in Everything for Famistudio.deu.ini

---

FamiStudio/Source/Player/RegisterWriteOptimizer.cs

VGM export now got proper EPSM SSG envelope handling 
also replaced code only intended for Mono (please wait until a comment when i test compile this for android)

EPSM envelope shape register fix

---

FamiStudio/Localization/FamiStudio.spa.ini

thanks to ma buddy lagmager for helping with this one!!

Finished Spa.ini Translation (4.2.0)

---

FamiStudio/Localization/FamiStudio.eng.ini

Fixed a lot of typos/grammatical errors in English (mostly related to singular/plural)

English localization

---

SoundEngine/famistudio_sdas.s

* Update famistudio_sdas.s to match note table filename changes done in 17eb16a9c67e50f4bc8fea070644d2fb30a4a722

Update note table filenames for sdas

---

FamiStudio/Localization/FamiStudio.spa.ini

Changed every "#TODO!", including "#MultiplePatternsSelectedLabel".

Update FamiStudio.spa.ini (Finished)

---

FamiStudio/Source/App/Common/Settings.cs
FamiStudio/Source/Project/Project.cs

Additionally bump settings version.

Fix mixer override serialization for old projects

---

FamiStudio/Localization/FamiStudio.deu.ini

Add German translations and fix spelling mistakes (Wilkommen -> Willkommen and NIcht -> Nicht)

German Translations 
